"""Tests for the Pydantic models in axis_b.schema."""

from __future__ import annotations

import json

import pytest
from pydantic import ValidationError

from axis_b.schema import TestCase, TestInput


def _full_test_case_data() -> dict:
    return {
        "tc_id": "TC-18013-5-7.2.1-001",
        "objective": "Verify that the mDL does not transmit data before engagement.",
        "priority": "High",
        "traceability": "iso_iec_18013_5_0042 (section 7.2.1)",
        "preconditions": [
            "mDL is provisioned with a valid driving licence",
            "mDL reader supports NFC device engagement",
        ],
        "inputs": [
            {
                "input_number": 1,
                "action": "Attempt a data request before device engagement.",
                "expected_result": "The mDL rejects the request and transmits no data.",
            },
            {
                "input_number": 2,
                "action": "Complete device engagement, then request data.",
                "expected_result": "The mDL responds with the requested data elements.",
            },
        ],
        "actual_results": "",
        "requirement_type": "SHALL",
        "coverage_item_id": "TCI-18013-5-7.2.1-001",
        "feature_set": "Device Engagement",
        "notes": "Generated by the Axis B pipeline.",
    }


def test_full_test_case_round_trip_without_loss() -> None:
    data = _full_test_case_data()
    tc = TestCase.model_validate(data)

    serialized = tc.model_dump_json()
    restored = TestCase.model_validate(json.loads(serialized))

    assert restored == tc
    assert restored.model_dump() == tc.model_dump()
    assert restored.model_dump() == data
    assert isinstance(restored.inputs[0], TestInput)
    assert restored.inputs[1].input_number == 2


def test_missing_shall_field_raises_validation_error() -> None:
    data = _full_test_case_data()
    del data["traceability"]  # SS7.3.5.5 SHALL field

    with pytest.raises(ValidationError):
        TestCase.model_validate(data)


@pytest.mark.parametrize(
    "shall_field", ["tc_id", "priority", "preconditions", "inputs", "coverage_item_id"]
)
def test_each_missing_shall_field_raises(shall_field: str) -> None:
    data = _full_test_case_data()
    del data[shall_field]

    with pytest.raises(ValidationError):
        TestCase.model_validate(data)


def test_invalid_priority_rejected() -> None:
    data = _full_test_case_data()
    data["priority"] = "Critical"

    with pytest.raises(ValidationError):
        TestCase.model_validate(data)


def test_extra_field_rejected() -> None:
    data = _full_test_case_data()
    data["unexpected"] = "schema drift"

    with pytest.raises(ValidationError):
        TestCase.model_validate(data)


def test_actual_results_defaults_to_empty_string() -> None:
    data = _full_test_case_data()
    del data["actual_results"]

    tc = TestCase.model_validate(data)
    assert tc.actual_results == ""
